---
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: 386
    ldflags:
      - -s -w -X 'github.com/ItsNotGoodName/smtpbridge/cmd.version={{.Version}}' -X 'github.com/ItsNotGoodName/smtpbridge/cmd.commit={{.Commit}}' -X 'github.com/ItsNotGoodName/smtpbridge/cmd.date={{.Date}}' -X 'github.com/ItsNotGoodName/smtpbridge/cmd.builtBy=goreleaser'
archives:
  - format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
